# name: "Ruby on Rails CI"
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - name: Setup Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.1.1
#           bundler-cache: true
#       - name: Install Node
#         uses: actions/setup-node@v2
#         with:
#           node-version: '12.16.x'
#       - name: Restore cached ./node_modules
#         uses: actions/cache@v2
#         with:
#           path: ./node_modules
#           key: ${{ runner.os }}-yarn-lock-${{ hashFiles('./yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-yarn-lock-
#       - name: Yarn Install
#         run: yarn install
#   test:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:11-alpine
#         ports:
#           - "5432:5432"
#         env:
#           POSTGRES_DB: rails_test
#           POSTGRES_USER: rails
#           POSTGRES_PASSWORD: password
#     env:
#       RAILS_ENV: test
#       RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
#       DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       # Add or replace dependency steps here
#       - name: Install Ruby and gems
#         uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
#         with:
#           ruby-version: 3.1.1
#           bundler-cache: true

#       # # Add or replace database setup steps here
#       # - name: Set up database schema
#       #   run: bin/rails db:schema:load

      

#       - name: Install dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y chromium-browser chromium-chromedriver
#           gem install bundler
#           bundle install --jobs 4 --retry 3

#       - name: Create and migrate database
#         run: |
#           bundle exec rake db:create
#           bundle exec rake db:migrate

#       # - name: Set up X Window System
#       #   uses: jakubstransky/xvfb-action@v1
      
#       # - name: Run RSpec with Selenium
#       #   env:
#       #     DISPLAY: ${{ env.XVFB_DISPLAY }}
#       #   run: bin/rails test:system
#       - name: Run Selenium tests
#         env:
#           SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub/
#         run: bin/rails test:system




#       # # Add or replace test runners here
#       # - name: Run tests      
#       #   run: bin/rails test:system 

#       # Add Code Coverage
#       - name: Create Coverage Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: code-coverage
#           path: coverage/


name: Rails CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.7
        env:
          POSTGRES_USER: myapp
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Setup Ruby and install gems
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: myapp
        run: |
          bin/rails db:setup

      - name: Run tests
        run: bin/rspec



