name: "Ruby on Rails CI 第一版"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Restore cached ./node_modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-lock-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-lock-
      - name: Yarn Install
        run: yarn install

      # # 這一行
      # - name: webpacker install
      #   run: rails webpacker:install
      
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          ruby-version: 3.1.1
          bundler-cache: true

      # # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load      

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Create and migrate database
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate

      - name: Run Selenium tests
        run: bundle exec rspec
      
      # Add Code Coverage
      - name: Create Coverage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/    




# name: "Ruby on Rails CI 第二版"
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:11-alpine
#         ports:
#           - "5432:5432"
#         env:
#           POSTGRES_DB: rails_test
#           POSTGRES_USER: rails
#           POSTGRES_PASSWORD: password
#     env:
#       RAILS_ENV: test
#       DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       # Add or replace dependency steps here
#       - name: Install Ruby and gems
#         uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
#         with:
#           ruby-version: 3.1.1
#           bundler-cache: true
#       # Add or replace database setup steps here
#       - name: Set up database schema
#         run: bin/rails db:schema:load
#       # Add or replace test runners here
#       - name: Run tests
#         # run: bin/rails test:system
#         run: bundle exec rspec


# name: tests
# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:
#     name: rspec
#     runs-on: ubuntu-latest

#     services:
#       postgres:
#         image: postgres
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: postgres
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5
#     steps:
#       - uses: actions/checkout@v2
#       - uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.1.1
#       - name: Install PostgreSQL
#         run: sudo apt-get -yqq install libpq-dev
#       - name: Run bundle install
#         run: |
#           gem install bundler
#           bundle install --jobs 4 --retry 3
#       - name: Run yarn commands
#         run: |
#           yarn install
#       - name: Setup Database
#         # env:
#         #   RAILS_ENV: test
#         #   POSTGRES_HOST: localhost
#         #   POSTGRES_USER: postgres
#         #   POSTGRES_PASSWORD: postgres
#         #   POSTGRES_DB: postgres
#         run: bin/rails db:create db:schema:load

#       - name: Build and test with rspec
#         env:
#           RAILS_ENV: test
#           POSTGRES_HOST: localhost
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: postgres
#           RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
#         run: bundle exec rspec


